// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://insncccrxgsvaxxkzjws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imluc25jY2NyeGdzdmF4eGt6andzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MTIzOTgsImV4cCI6MjA1MzM4ODM5OH0.DPaXLXAl2c4hJBS7oye_r5NxopL96DSr0A_SLAwUA7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);